# Generated by Django 3.2 on 2024-02-04 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='pages',
            constraint=models.UniqueConstraint(fields=('page',), name='unique_page'),
        ),
    ]
